### ISSUE TITLE
Implementare gestione di tutti i repo

### ISSUE THREAD

**Issue by VaiTon** [cartabinaria/fileseeker#1]
Al momento l'url è hardcodato. E' necessario integrare il repo `config` e predisporre tante path e tanti filesystem quanti sono gli insegnamenti.

**Comment by lucat1** [comment]
Userei un router tipo [kataras/muxie](https://github.com/kataras/muxie) e parametrizzerei sul corso.
All'avvio possiamo leggere il json (che embedderei nel binario go con [embed](https://pkg.go.dev/embed)) e crei una mappa corso : url tipo. In realtà si potrebbe fare anche senza il json e la mappa, però poi faremo richieste inutili a url sbagliati se la gente provasse ad accedere a una repo che non esiste.

**Comment by VaiTon** [comment]
In https://github.com/csunibo/fileseeker/commit/7e9b56ce6f6f69d554e44ea1462dc3c00418955f ho fatto un FS dummy che lista delle stringhe, che a loro volta sono i titoli dei repo.
