### ISSUE TITLE
Non funziona con il nuovo formato dei corsi

### ISSUE THREAD

**Issue by VaiTon** [cartabinaria/fileseeker#20]
Da quando abbiamo diviso il file `courses.json` il software non va

**Comment by foxyseta** [comment]
Ammesso che fileseeker sia ancora sviluppato, potremmo approfittare delle investigazioni su questo problema per usare config come modulo go anziché sottomodulo git.

**Comment by VaiTon** [comment]
@foxyseta il codice nuovo è sul branch local_files e l'ho fatto funzionare con la nuova config. Ora faccio una pull request.
